#! /bin/bash
JDK_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0

if [[ ! -L $JDK_HOME && ! -d $JDK_HOME ]]
  then
  cd $OPENSHIFT_DATA_DIR
  wget http://www.java.net/download/jdk8u20/archive/b17/binaries/jdk-8u20-ea-bin-b17-linux-x64-04_jun_2014.tar.gz
  tar xvf *.tar.gz
  rm -f *.tar.gz
  ln -s jdk1.8.0_20 jdk1.8.0
fi